### ISSUE TITLE
BetterCombat mod incompatibility

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [CleverNucleus/RelicEx#11]
Hello!
Better Combat and RelicEx have a conflicting mixin over `LivingEntityRender.features` `GETFIELD`
https://github.com/ZsoltMolnarrr/BetterCombat/issues/50

As far as I can see this comes from RelicEx using a custom ArmorRenderer lib.
Is there a reason why not fabric API is used for custom armor rendering?

**Comment by CleverNucleus** [comment]
Hi there,
Thanks for bringing that to my attention; I've modified Armor Render Lib so that it no longer uses that mixin. Indeed, Armor Render Lib no longer causes a cascading crash when loaded with BetterCombat.

Regarding custom armor rendering, Armor Render Lib only extends Fabric API's implementation - as there are objects I need to reference down the road that are not otherwise passed through with Fabric API. Basically it's a more fleshed out interfacer for Fabric API's custom armor rendering.

I'll be outputting the fixed releases later today, along with RelicEx, and then our mods will be compatible.
Cheers.

**Comment by ZsoltMolnarrr** [comment]
Thanks for the fix, highly appreciated!
