### ISSUE TITLE
I tried to put a cloak on, and the game crashed. (1.19 RelicEx 3.2.3)

### ISSUE THREAD

**Issue by MemeLord32** [CleverNucleus/RelicEx#12]
https://pastebin.com/DtVsqg1e

That is the crash report. I put a cloak on that increases dexterity, and now it crashes every time I open my inventory.

I disabled the mod I thought was having a problem with it, it still crashes whenever I open the inventory.

**Comment by CleverNucleus** [comment]
Hi there,
This is probably an issue with the library that RelicEx ships with, but could you please provide a modlist (including the version of Fabric API and RelicEx) that you are using?
Thanks.

**Comment by MemeLord32** [comment]
https://pastebin.com/XQBeeRaQ < - My obscenely long modlist

Fabric Api 0.58.0+1.19 and RelicEx 3.2.3 are what I'm using.

I downloaded and installed armor render lib thinking it would fix the problem, but it didn't. I just left it in there, but I'll remove it at a later date.

**Comment by CleverNucleus** [comment]
Hi there,
Thank you for providing the mod list, I will continue looking into the crash.

**Comment by MemeLord32** [comment]
Thank you.

**Comment by CleverNucleus** [comment]
Hi again,
Just to confirm, the "cloak" you put on that increased dexterity was definitely one of the RelicEx Relic items? It wasn't another item from a different mod, such as Artifacts?
Thanks.

**Comment by CleverNucleus** [comment]
Just to provide an update on this issue, the crash is caused by incompatibility with Geckolib - fix should come soon.

**Comment by TalEdd** [comment]
I have the exact same error, I think. 
`java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1309.method_6118(net.minecraft.class_1304)" because "this.gl_storedEntity" is null`
 Was just about to make an issue when I saw this post.😆

**Comment by CleverNucleus** [comment]
Hi there,
I was unable to replicate this crash. However, the logs many of you have provided clearly showed that it was happening and that it was an issue caused by Armor Render Lib (embedded in RelicEx) and GeckoLib. Additionally, the logs showed what part of the code was responsible. I have since removed that part of the code and have refactored Armor Render Lib such that there is no possibility of it interfering with Geckolib.

However, since I could not actually replicate this crash in the first place, I have not been able to verify for sure that RelicEx no longer causes this crash - but I think that it *probably* won't. 😆 

Updated releases are available on Modrinth, pending approval on Curseforge.
Thanks.
