### ISSUE TITLE
Wrong tooltip' display on Ring Relic

### ISSUE THREAD

**Issue by Rivmun** [CleverNucleus/RelicEx#19]
Game Version: 1.19.2
API: Fabric 0.14.9
The tooltip of Ring Relic display like this:
![QQ截图20220918192903](https://user-images.githubusercontent.com/113169310/190899844-e54ed462-f398-45ad-94d3-b6f61f9abf7a.jpg)
And other like:
![QQ截图20220918192917](https://user-images.githubusercontent.com/113169310/190899923-9f7e9837-d38b-45bb-8b22-e62328fd944a.jpg)
Seems title is missing and rare tag on wrong position.
This is my [modlist.txt](https://github.com/CleverNucleus/RelicEx/files/9593863/modlist.txt)

**Comment by Rivmun** [comment]
I tried to switch language to English then it won't happened. So, it seems cause by language file execution of Trinket or RelicEx.
Pic 1 line 3 “可装备在以下槽位:" ("Equippable in the trinket slots:" in English) is quoted from Trinket. Which is won't be shown  in English lang, like pic 2.
Both mod is translated by me from en_us.json word by word. I don't know why is has such a problem.

**Comment by CleverNucleus** [comment]
Hi there,
I'll start by saying that I have absolutely no clue why this is happening. The fact that it works fine for English translation but not the other is baffling, more so because the language that is being used should have _no programmatical relevance_. I also cannot see any mods from your list that would be interacting with RelicEx to cause this.

I'll continue looking into it, but I don't see a solution any time soon.
Nonetheless, thank you for bringing this to my attention.

**Comment by CleverNucleus** [comment]
Closed as issue is stale: fix is unlikely and issue is non-critical.
