### ISSUE TITLE
Head slot relics not working

### ISSUE THREAD

**Issue by Soggyshorts** [CleverNucleus/RelicEx#30]
I've found 4 head relics so far, and they don't seem to do anything.
+16% lifesteal and +5 STR for example, but swapping relics or just unequipping doesn't change my stats.

The necklaces I've found all work great, am I missing something?

 

Love the mods BTW, thanks!

**Comment by CleverNucleus** [comment]
Hi there,
Could you specify what version of Data Attributes, PlayerEx and RelicEx you are using?
Thanks.

**Comment by Soggyshorts** [comment]
data-attributes-1.2.8
playerex-3.3.8
relicex-3.2.6

**Comment by CleverNucleus** [comment]
Hi there,
I've done some testing and cannot replicate this issue. Do you have any other mods installed that you think may cause some incompatibility resulting in this behaviour? For example, AttributeFix is incompatible with Data Attributes and could cause issues like this.
Thanks.

**Comment by Soggyshorts** [comment]
I was hoping it was something easy.  We've updated to the latest versions but we're having the same issue.
Must be one of our other mods then, not sure which. Unfortunately, there are a lot of them...
https://pastebin.com/bhn4LKQF
If any of those jumps out at you I can test it out

**Comment by CleverNucleus** [comment]
I think the ones that jump out for me are RPGStats, Spoorn Armor Attributes and Spoorn Weapon Attributes. RPGStats in particular because it and PlayerEx essentially do the same things, and Spoorn _ Attributes because just glancing at the mixins I can see they're messing with attribute values.

I'd try it without those mods and see if it works. Also, how is the issue manifesting, specifically? Are you equipping the head relic and then checking the attributes screen and there's no change in the attribute number? Or is it that there is a change in the attribute number but that change isn't being reflected in actual gameplay (i.e., you get an increase in lifesteal but then notice you aren't healing when attacking)?.
Thanks.

**Comment by Soggyshorts** [comment]
Ooooh I've got it figured out: [ PEBCAC](https://idioms.thefreedictionary.com/PEBCAC#:~:text=An%20initialism%20of%20%22problem%20exists,are%20using%20the%20machine%20incorrectly.)
We added Cosmetic Armor as well, and I mistakenly thought I could wear a helmet & a head relic at the same time. It turns out I was putting the Relic in the cosmetic slot :-(
Sorry for wasting your time, and thanks again for the great mods!

**Comment by CleverNucleus** [comment]
Ahah no problem at all, glad you figured it out.
