### ISSUE TITLE
Affix

### ISSUE THREAD

**Issue by Uhntil** [CleverNucleus/RelicEx#43]
hey im not sure if youre aware or if im doing something wrong but im doing exactly as the instructions say to affix relics to armor and its not working as ive tried many ways

**Comment by CleverNucleus** [comment]
Hi there,
What exactly have you tried? Do you have screenshots perhaps? What version of RelicEx are you using? I need more specifics if I am to help.
Thanks.

**Comment by Uhntil** [comment]
ive tried the normal crouch and right click, ive tried it on the item, ive switched armor positions, ive tried it in off hand, ive tried it as if switching items in the inventory, ive tried left clicking and even the sprint key, using a mythic head relic on a normal unenchanted iron helmet, ive tried in and out of inventory, version 3.3.1, on 1.19.2,

**Comment by CleverNucleus** [comment]
Hi there,
Since version 3.2.7, relics are affixed to armour using a _smithing table_, the same way you upgrade diamond armour to netherite. 

This is on me - I've just realised that the mod page description was never updated to reflect this. I appreciate it being brought to my attention.

Hope that helps,
Thanks.
