### ISSUE TITLE
Crash on Creeper Death

### ISSUE THREAD

**Issue by rauflb14** [CleverNucleus/RelicEx#9]
I had two crashes.
The first crash happend when the creeper blew up by himself. The second was i think because it was killed either by falling or getting shot by a skeleton.

[first crash](https://github.com/CleverNucleus/RelicEx/files/9336875/crash-2022-08-15_12.53.07-server.txt)

[second crash](https://github.com/CleverNucleus/RelicEx/files/9336873/crash-2022-08-15_13.24.55-server.txt)

**Comment by CleverNucleus** [comment]
Hi there,
This issue should now be resolved as of release 3.1.2 and 3.2.2.
Thanks.

**Comment by DadoIrie** [comment]
seems like https://github.com/CleverNucleus/RelicEx/issues/8
`java.lang.ClassCastException: class java.lang.Float cannot be cast to class java.lang.Double (java.lang.Float and java.lang.Double are in module java.base of loader 'bootstrap')
  at net.minecraft.class_1309.handler$icj000$relicex_dropLoot(class_1309.java:41570)`
  and tested it out now and should be fixed with the latest version

**Comment by DadoIrie** [comment]
![image](https://user-images.githubusercontent.com/61109153/184629454-e48614f7-b9c5-41b4-9ed2-e327030b86f7.png)

**Comment by rauflb14** [comment]
thank you, sorry, did not see that other issue
